# Generated by Django 4.2.19 on 2025-02-09 16:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(1, '普通用户'), (2, 'VIP会员'), (3, 'SVIP会员   ')], default=1, unique=True, verbose_name='会员等级')),
                ('name', models.CharField(max_length=10, verbose_name='会员等级名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('project_num', models.PositiveIntegerField(verbose_name='支持创建的项目最大个数')),
                ('project_member', models.PositiveIntegerField(verbose_name='支持项目成员最大个数')),
                ('single_project_space', models.PositiveIntegerField(help_text='单位为GB', verbose_name='单项目空间大小最大值')),
                ('single_file_space', models.PositiveIntegerField(help_text='单位为MB', verbose_name='单文件空间大小最大值')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=10, verbose_name='项目名称')),
                ('project_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目描述')),
                ('project_color', models.SmallIntegerField(choices=[(1, 'red'), (2, 'orange'), (3, 'yellow'), (4, 'green'), (5, 'blue'), (6, 'indigo'), (7, 'purple')], default=1, verbose_name='项目颜色')),
                ('remain_space', models.PositiveIntegerField(help_text='单位为kb', verbose_name='剩余空间')),
                ('join_number', models.PositiveIntegerField(default=1, verbose_name='项目成员数量')),
                ('star', models.BooleanField(default=False, verbose_name='项目是否星标')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bucket_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='项目对应的OSS存储桶')),
                ('region', models.CharField(default='cn-wuhan-lr', max_length=64, verbose_name='项目所属区域')),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('depth', models.PositiveIntegerField(default=0, verbose_name='文档层级')),
                ('father_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.wiki', verbose_name='父文档')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('member_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.memberlevel', verbose_name='会员等级')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '处理中')], verbose_name='交易状态')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易金额')),
                ('transaction_begin', models.DateTimeField(blank=True, null=True, verbose_name='订单实际支付时间')),
                ('transaction_end', models.DateTimeField(blank=True, null=True, verbose_name='会员实际结束时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.BooleanField(default=False, verbose_name='该成员是否星标')),
                ('member_join_time', models.DateTimeField(auto_now_add=True, verbose_name='成员加入时间')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='web.userinfo', verbose_name='邀请人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='web.userinfo', verbose_name='成员')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='项目负责人'),
        ),
        migrations.CreateModel(
            name='FileRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('file_type', models.SmallIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(blank=True, help_text='单位为字节', null=True, verbose_name='文件大小')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径')),
                ('key', models.CharField(blank=True, max_length=128, null=True, verbose_name='OSS对象存储的key')),
                ('file_extension', models.CharField(blank=True, max_length=32, null=True, verbose_name='文件后缀')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.filerepository', verbose_name='父文件夹')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='所属项目')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='最后更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
