# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-01-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(1, '普通用户'), (2, 'VIP会员'), (3, 'SVIP会员   ')], default=1, unique=True, verbose_name='会员等级')),
                ('name', models.CharField(max_length=10, verbose_name='会员等级名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('project_num', models.PositiveIntegerField(verbose_name='支持创建的项目最大个数')),
                ('project_member', models.PositiveIntegerField(verbose_name='支持项目成员最大个数')),
                ('single_project_space', models.PositiveIntegerField(help_text='单位为GB', verbose_name='单项目空间大小最大值')),
                ('single_file_space', models.PositiveIntegerField(help_text='单位为MB', verbose_name='单文件空间大小最大值')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=10, verbose_name='项目名称')),
                ('project_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目描述')),
                ('project_color', models.SmallIntegerField(choices=[(1, '红色'), (2, '橙色'), (3, '黄色'), (4, '绿色'), (5, '蓝色'), (6, '靛色'), (7, '紫色')], default=1, verbose_name='项目颜色')),
                ('remain_space', models.PositiveIntegerField(default=0, help_text='单位为MB', verbose_name='剩余空间')),
                ('join_number', models.PositiveIntegerField(default=1, verbose_name='项目成员数量')),
                ('star', models.BooleanField(default=False, verbose_name='项目是否星标')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_join_time', models.DateTimeField(auto_now_add=True, verbose_name='成员加入时间')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '处理中')], verbose_name='交易状态')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易金额')),
                ('transaction_begin', models.DateTimeField(blank=True, null=True, verbose_name='订单实际支付时间')),
                ('transaction_end', models.DateTimeField(blank=True, null=True, verbose_name='会员实际结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('member_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.MemberLevel', verbose_name='会员等级')),
            ],
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='web.UserInfo', verbose_name='邀请人'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='web.UserInfo', verbose_name='成员'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='项目负责人'),
        ),
    ]
