# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-01-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_color',
            field=models.SmallIntegerField(choices=[(1, 'red'), (2, 'orange'), (3, 'yellow'), (4, 'green'), (5, 'blue'), (6, 'indigo'), (7, 'purple')], default=1, verbose_name='项目颜色'),
        ),
    ]
