# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-01-16 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20250116_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='star',
            field=models.BooleanField(default=False, verbose_name='该成员是否星标'),
        ),
    ]
