# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-01-19 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20250119_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='depth',
            field=models.PositiveIntegerField(default=0, verbose_name='文档层级'),
        ),
    ]
