# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-01-26 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_project_bucket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='bucket',
            new_name='bucket_name',
        ),
    ]
