# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-02-03 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20250126_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='文件或文件夹名称')),
                ('file_type', models.SmallIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(blank=True, help_text='单位为字节', null=True, verbose_name='文件大小')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径')),
                ('key', models.CharField(blank=True, max_length=128, null=True, verbose_name='OSS对象存储的key')),
                ('file_extension', models.CharField(blank=True, max_length=32, null=True, verbose_name='文件后缀')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.FileRepository', verbose_name='上级目录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='所属项目')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='最后更新者')),
            ],
            options={
                'verbose_name': '文件库',
                'verbose_name_plural': '文件库',
            },
        ),
    ]
